export enum COUNTRIES {
  VIETNAM = "vietnam",
  UNITED_STATES = "united_states",
  UNITED_KINGDOM = "united_kingdom",
  JAPAN = "japan",
  SOUTH_KOREA = "south_korea",
  CHINA = "china",
  FRANCE = "france",
  GERMANY = "germany",
  CANADA = "canada",
  AUSTRALIA = "australia",
  SINGAPORE = "singapore",
  THAILAND = "thailand",
  INDONESIA = "indonesia",
  MALAYSIA = "malaysia",
  PHILIPPINES = "philippines",
  INDIA = "india",
}
