import { CERTIFICATE_TEMPLATES } from "@/enums";
export const CERTIFICATE_TEMPLATE_LABELS = {
  [CERTIFICATE_TEMPLATES.IELTS]: "ielts",
  [CERTIFICATE_TEMPLATES.TOEIC]: "toeic",
  [CERTIFICATE_TEMPLATES.GRADUATION_CERTIFICATE]: "graduation_certificate",
};

export const CERTIFICATE_TEMPLATES_OPTIONS = [
  {
    value: CERTIFICATE_TEMPLATES.IELTS,
    label: CERTIFICATE_TEMPLATE_LABELS[CERTIFICATE_TEMPLATES.IELTS],
  },
  {
    value: CERTIFICATE_TEMPLATES.TOEIC,
    label: CERTIFICATE_TEMPLATE_LABELS[CERTIFICATE_TEMPLATES.TOEIC],
  },
  {
    value: CERTIFICATE_TEMPLATES.GRADUATION_CERTIFICATE,
    label:
      CERTIFICATE_TEMPLATE_LABELS[CERTIFICATE_TEMPLATES.GRADUATION_CERTIFICATE],
  },
];

export const DEFAULT_CERTIFICATE_TEMPLATE =
  CERTIFICATE_TEMPLATES.GRADUATION_CERTIFICATE;
