export const QUERY_KEYS = {
  GET_MY_PROFILE: "GET_MY_PROFILE",

  GET_ALL_USERS: "GET_ALL_USERS",
  GET_DELETED_USERS: "GET_DELETED_USERS",
  GET_USER_BY_ID: "GET_USER_BY_ID",
  GET_REGISTRATION_BY_ID: "GET_REGISTRATION_BY_ID",
  GET_ALL_REGISTRATIONS: "GET_ALL_REGISTRATIONS",
  GET_MY_ORGANIZATIONS: "GET_MY_ORGANIZATIONS",
  GET_ALL_ORGANIZATIONS: "GET_ALL_ORGANIZATIONS",
  GET_ORGANIZATION_MEMBERS: "GET_ORGANIZATION_MEMBERS",
  GET_ALL_CERTIFICATE_TYPES: "GET_ALL_CERTIFICATE_TYPES",
  GET_CERTIFICATE_TYPE: "GET_CERTIFICATE_TYPE",
  GET_ORGANIZATION_CERTIFICATES: "GET_ORGANIZATION_CERTIFICATES",
  GET_CERTIFICATE_REQUESTS: "GET_CERTIFICATE_REQUESTS",
  GET_CERTIFICATE_REQUESTS_SPECIFIC: "GET_CERTIFICATE_REQUESTS_SPECIFIC",
};
