import { CERTIFICATE_ADDITIONAL_FIELD, COUNTRIES } from "@/enums";

export type CertificateItemFormType = {
  authorName: string;
  authorIdCard: string;
  authorDob: Date | null | string;
  authorEmail: string;
  authorCountryCode: COUNTRIES;
  authorImage?: string;
  grantLevel: string | number;
  domain?: string;
  isError?: boolean;

  // additional field
  [CERTIFICATE_ADDITIONAL_FIELD.SERIAL_NUMBER]?: string;
  [CERTIFICATE_ADDITIONAL_FIELD.REG_NO]?: string;

  [CERTIFICATE_ADDITIONAL_FIELD.CENTRE_NUMBER]?: string;
  [CERTIFICATE_ADDITIONAL_FIELD.CANDIDATE_NUMBER]?: string;
  [CERTIFICATE_ADDITIONAL_FIELD.CANDIDATE_SEX]?: string;
  [CERTIFICATE_ADDITIONAL_FIELD.ORIGIN_COUNTRY]?: string;
  [CERTIFICATE_ADDITIONAL_FIELD.FIRST_LANGUAGE]?: string;
  [CERTIFICATE_ADDITIONAL_FIELD.LISTENING_RESULT]?: string;
  [CERTIFICATE_ADDITIONAL_FIELD.READING_RESULT]?: string;
  [CERTIFICATE_ADDITIONAL_FIELD.WRITING_RESULT]?: string;
  [CERTIFICATE_ADDITIONAL_FIELD.SPEAKING_RESULT]?: string;
  [CERTIFICATE_ADDITIONAL_FIELD.ADMINISTRATOR_COMMENTS]?: string;
  [CERTIFICATE_ADDITIONAL_FIELD.TEST_REPORT]?: string;
};
